CREATE TABLE IF NOT EXISTS users(
    id int UNIQUE NOT NULL,
    F_name VARCHAR(50) NOT NULL,
    F_name VARCHAR(50) NOT NULL,
    user_name VARCHAR(50) UNIQUE NOT NULL,
    pass_word VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);